FROM node:20-alpine

RUN npm install -g pnpm@10.27.0

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY prisma ./prisma

RUN pnpm run db:generate

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["pnpm", "run", "dev"]
